### ISSUE TITLE
Can't upgrade certain units

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#147]
Ok so you are stuck with a 2 flak38 in the Das Reich campaign. All I want to do is put the fucker in a faster transport but it WILL Not let me.

**Comment by LaughtersGrave** [comment]
I don't know how to add screen shots or I would post it

**Comment by LaughtersGrave** [comment]
Oh no I get it on both the open panzer app and in the browser version

**Comment by salexgit** [comment]
Hi LaughtersGrave

What I meant is that this inconsistency (assuming we talk about the same problem) was fixed and has been under testing in the offline package that you can find here: 
https://sites.google.com/openpanzeroffline

So, I would be more than grateful if you check and confirm whether the aforementioned version addresses your concerns, because then we can prioritize adding these corrections into the official game version.

**Comment by LaughtersGrave** [comment]
That link says 404 Google can't find the site :(

**Comment by salexgit** [comment]
Hi

Sorry, there was a typo, here is a correct link:
https://sites.google.com/site/openpanzeroffline

**Comment by LaughtersGrave** [comment]
Ok so I downloaded this one:
"Description: This package contains completely re-generated "DasReich" campaign files taken from the latest SCN files. It fixes a number of issues with unit types, especially transport units. There are also fixes for issues #138 and #140"

Do I just drag and ask the files into where open panzer app is on my phone?

**Comment by LaughtersGrave** [comment]
![screenshot_2018-10-10-01-49-08-738_com ecosia android](https://user-images.githubusercontent.com/44041995/46811990-b82dbc80-cd6b-11e8-98b9-2364d24437cc.png)

I got a screen shot of the original issue on the app and in browser. 

See the transport is there... But the upgrade button isn't. It doesn't make sense

**Comment by salexgit** [comment]
Hi

Can you tell me the scenario from which you took that screenshot?

By the way, at least according to the attached screenshot, 2 flak38 unit already has H830B as the transport unit attached to it, so I am not sure what you problem is.

**Comment by salexgit** [comment]
Hi again

Ok, now I finally got what the problem is, sorry for taking so much time...

I do not know whether it is a bug or feature, but you indeed cannot upgrade transport type of a particular unit. In other words you can upgrade the transport type while upgrading the unit, but you cannot change only the transport. Let me check how it works for the original Panzer General II game. 

Anyway, it can be considered as an enhancement to the game. Thanks for spotting it :)

**Comment by salexgit** [comment]
Hi Nicu

I experimented a bit and noticed that for some units you can upgrade transport but for some units you cannot! 

I opened the first scenario from the DasReich campaign, you cannot upgrade transport type at least for following unit - 2 Flak 38  - as initially triggered by this thread. Other unit types are upgradeable, but I did not check all of them. 

Is it controlled by a unit attribute or is it just some weird coincidence of facts for this particular unit type?

**Comment by LaughtersGrave** [comment]
I have the transport upgrade button not appearing for 2 flak38 and for some reason I can't change ss infantry to landwher. I know that's not sensible, but a player should be able to do it in order to gain some prestige back (also called downgrading) this was realistic practice in the army where bad units would replace good ones and the commander would get an "IOU" which in this case, is prestige. 

Even if it's not a good move, it should be allowed. 

Thanks again 
Salexgit
And 
Thank you nicu

I look forward to being able to upgrade my 2 flak38 transport soon :)

**Comment by LaughtersGrave** [comment]
@salexgit how do I unpack the offline files into my game to make them work? I assume you can't on the browser which leaves the app, so how do I do that

**Comment by LaughtersGrave** [comment]
Ok so I used your link to Google drive, downloaded and then extracted the offline package file  (the Das Reich one). I tried running the index, the win_chrome.Bat and the win_firefox.bat. I tried them all in ecosia and Google chrome browsers. None of them worked. See screen shots below 

![screenshot_2018-10-12-21-09-17-247_com android chrome](https://user-images.githubusercontent.com/44041995/46892262-b72c8600-ce64-11e8-98b1-3fa0bd67684b.png)
![screenshot_2018-10-12-21-12-18-156_com android chrome](https://user-images.githubusercontent.com/44041995/46892270-bd226700-ce64-11e8-9ac8-9f60c3e58357.png)
![screenshot_2018-10-12-21-12-34-718_com ecosia android](https://user-images.githubusercontent.com/44041995/46892286-c90e2900-ce64-11e8-8074-38b8218cb8ad.png)

**Comment by salexgit** [comment]
Hi LaughtersGrave 

Let's make several steps back... 
The bug that you reported is a new one, and the offline package that you try to install on the mobile phone will not anyway fix it. However, the corrections from the offline package might be added soon to the official version, so I suggest you just to wait :)

Regards, Alex

**Comment by salexgit** [comment]
Hi LaughtersGrave

This issue has been fixed in the online 2.9.9 beta version. It would be nice if you also check and confirm that it works properly now:
http://openpanzer.net/beta/

**Comment by LaughtersGrave** [comment]
![screenshot_2018-10-26-21-55-27-005_com ecosia android](https://user-images.githubusercontent.com/44041995/47592208-37291480-d96a-11e8-8ac9-5db0ca270a8a.png)


Sorry but it is not fixed. As you can see here the upgrade button is entirely missing from the 2 flak38 still

**Comment by salexgit** [comment]
Hi

True, I must have confused this unit with something else falsely assuming that the problem has been fixed.

@nicupavel: I noticed that "2 flak 38" does not appear at all at the list anti-air units, at appears only at the list of units you have. If I remember right, the equipment file has a special unit attribute "is purchasable" which controls whether a unit appears on the list of available unit types. Can it be the case that this unit has this attribute and thus it can be neither purchased nor upgraded?

**Comment by LaughtersGrave** [comment]
If it can never be upgraded its pointless to have, that must clearly be a mistake

**Comment by salexgit** [comment]
Hi LaughtersGrave

The way the game works is that any military entity you can see on a map including bunkers and roadblocks are units. However, you cannot buy bunkers or roadblocks, neither can you upgrade them even if you have the one. 
Let me double-check that Flak unit. I suspect that it has been (mistakenly?) marked as non-purchasable unit resulting in such a behavior.

**Comment by salexgit** [comment]
Hi again

I did some further debugging and I found the reason why certain unit types could not be upgraded. However, I am not sure whether it is intentional or not.

So, most of the anti-air unit types are marked internally as "anti-air", but there are four units  which are marked internally as "flak". I was trying to find in the Open General document what the difference is, but I failed. Anyway, it seems that OpenPanzer game engine does not allow you buying/upgrading unit of the "flak" type.

Just out of curiosity, I changed "2 flak 38" unit type from "flak" to "anti-air", and it worked as expected. As you can see from the attached screenshot, you can buy/upgrade "2 flak 38".

![flak](https://user-images.githubusercontent.com/22852936/47612339-3cc54e00-da81-11e8-9b00-aed79025705c.png)

@nicupavel There are four units (see their ID belows) which for some reason have unit type "flak", other Flak units are marked as "anti-air". Maybe you know the history and the reason behind it, because as for me it is just a mistake or some weird inconsistency. Can you mark this discussion thread as "equipment, bug" so that we do not forget about fixing it?

64       2 Flak 38
65       2 Flakvierling38
2787   2 Flak38 LKW
2797   2 Flak30

**Comment by nicupavel** [comment]
There is a separate equipment category called Flak. These units can only be upgraded to Air Defense units but can't be bought separately. The flak category was designed for static air defence in air fields/cities etc it's not supposed to be in your core army.

**Comment by LaughtersGrave** [comment]
Historically 2 flak38 is man portable (you see one in private Ryan being used against the troops climbing onto the tank, the T-34 they did up to look like a Tiger 1)

The flakvierling 38 was also a highly portable anti air gun that was frequently mounted on flat beds.

It would make no sense for these to be stationary for the entire game. 

I would offer my opinion that these simply be moved to anti air category.

**Comment by salexgit** [comment]
Hi all

Abstracting from how things are modeled in the game, here is a link to Wikipedia that describes quite eloquently that most of the Flak units are _not_ stationary. There is even a separate section on "mounting versatility" detailing further that multiple transportation options existed. 
https://en.wikipedia.org/wiki/2_cm_Flak_30/38/Flakvierling

The only really stationary Flak unit is 12.8 Flak 40 (see the link below), which in some exceptional cases was mounted on rail cars, which is anyway not supported by the game engine.
https://en.wikipedia.org/wiki/12.8_cm_FlaK_40

Now back to game... Whatever reason behind introduction of "flak" unit class is, its usage is a bit obscure and inconsistent, as far as I can see. In fact, stationary unit behavior can modeled with "anti-air" unit with zero movement and no transportation options assigned. Furthermore, you can even prevent a unit from being purchased by assigning the corresponding unit attribute. 

Initially I thought that the only reason why we need "flak" versus "anti-air" is because Flak units were so versatile that they could attack both air and also ground units. They were used as anti-tank guns as well. Anyway, to my knowledge the game engine does not support it at the moment, which brings us back to the initial point why some Flak units are classified as "flak" and some of them are "anti-air".

**Comment by LaughtersGrave** [comment]
I have found that I can attack ground and air targets with the 2 flak38. I tried upgrading to the 8.8cm and could not. Which again doesn't make sense, as you said the point of the flak was that it was used against both ground and air targets.

The flakvierling on the truck mount or half track was frequently used as an exceptionally effective anti personnel weapon, as well as anti aircraft. 

I agree with you 100%

I thin the way to fix this issue is to make any historical flak wagon available to the player as a purchase at the correct time frame (except fixed mounts of which, as you say there are none in game) 

Anything in the core army should be able to upgrade and downgrade as per history. 

I would like to downgrade my ss to Landwher (for the super fast transports, I use them to capture empty towns for prestige) 

I'd like to have my 2cm flak38 in something quicker than a donkey :/

Ah well. 

Once again, I agree with what Salexgit has said, flak are meant to be able to attack both ground and air and extremely portable for the most part.

I would really like to see them implemented as such.

**Comment by nicupavel** [comment]
I'm not sure why you can't upgrade 2 flak38. I guess you are referring to the one in first scenario from Das Reich campaign, which I upgraded to 8.8Flak. 
![screen shot 2018-10-30 at 9 01 10 pm](https://user-images.githubusercontent.com/1650801/47743157-1244e200-dc87-11e8-9185-25cd68930992.png)

**Comment by LaughtersGrave** [comment]
@nicupavel   OK but try not upgrading the gun but putting it in a different transporter. You can't. Also try attacking ground targets with the 8.8 you can't. It doesn't make sense

**Comment by salexgit** [comment]
Hi all

I investigated a bit current equipement file - it is messed up with regards to the Flak and anti-air units.

The first discrepancy comes from the fact that some Flak units are classified internally as "flak" whereas other Flak units are classified as "anti-air". 
The second part of whole puzzle is game engine. Game engine allows "flak" units to attack both air and ground units, and that is why it works for 2 Flak38. However, game engine does not allow "anti-air" units to attack ground targets. That is why you cannot do it with 8.8 Flak. Furhermore, game engine hides "flak" units and that is why you cannot upgrade or buy them.
So, it is very messed up and I am not getting reluctance to fix it.

I have not analyzed the overall code impact, but the workplan might look as follows:
- we classify all Flak units as "flak" so that they can attack both air and ground units;
- the game engine must be enhanced so that "flak" units are treated normally

I can assist with the first item but the second one will definitely be Nicu's task.

**Comment by nicupavel** [comment]
In PG2 Anti-aircraft (flak) could attack both air and ground, air defense units could only attack air. So we follow the same rules except the upgrade possibility.

This kind of changes must be thought with the entire equipment in mind not only German side.

**Comment by salexgit** [comment]
Hi Nicu

I am not advocating changing the rules which are fine. The point I have been trying to make is that some Flaks unit - such as 8.8 Flak 36 - are not modelled internally as "flak" and thus they do not behave as Flaks and cannot attack ground units. In fact, 8.8 Flak 36 is even messier because instead of having one "flak" unit, we have two units of "anti-air" and "anti-tank" type. 

I can help in polishing the equipment files. We can start with German units, make changes, test them in online beta, and once we know it works as expected we can expand it towards similar units from other nations.

As I noted earlier, the game engine must be anyway enhanced to allow for buying/upgrading "flak" units.

**Comment by LaughtersGrave** [comment]
Salexgit is right
